#!/bin/bash
test_name="DEC Tests"
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ASM="${script_dir}/test_dec.asm"
BIN="${script_dir}/test_dec.bin"
OUTPUT="${script_dir}/result.asm"
OUTPUT_BIN="${script_dir}/result.bin"
GLOBALS="${script_dir}/../globals.sh"

source "${GLOBALS}"

# Assemble test_mov.asm into a binary 
if ! nasm "${ASM}" -o "${BIN}"; then 
    echo "ERROR::Failed to assembled ${ASM}."
    exit 1
fi

# Run 8086 simulator decode
if ! "${SIM_EXE}" -d "${BIN}" "${OUTPUT}"; then
    echo "ERROR::Could not disassemble ${BIN}."
    exit 1
fi

# Assemble output 
if ! nasm "${OUTPUT}" -o "${OUTPUT_BIN}"; then
    echo "ERROR::Coult not assemble ${OUTPUT_BIN}"
    exit 1
fi 

# Compare original bin to generated bin 
if cmp -s "${OUTPUT_BIN}" "${BIN}"; then 
    echo "${test_name} ...... SUCCESS"
    # Cleanup artifacts generated by simulator run 
    rm -rf "${OUTPUT}" "${OUTPUT_BIN}"
else 
    echo "${test_name} ....... FAIL"
    exit 1
fi 